### ISSUE TITLE
add ngx_waf module

### ISSUE THREAD

**Issue by ghost** [u-sb/nginx-docs#1]
Can nginx.io  integrates this module like geoip2, brotli?
https://github.com/ADD-SP/ngx_waf

**Comment by Showfom** [comment]
Thank you for your advice. We need extra time to test this module.

**Comment by Showfom** [comment]
I just tested ngx_waf, it's working fine with our Nginx repo

```
git clone https://github.com/ADD-SP/ngx_waf
cd ngx_waf
sh assets/download.sh 1.21.5 current
```

You need to install `libmodsecurity3`

```
apt install libmodsecurity3
```
