### ISSUE TITLE
Feedback for “Installation” (quic beta)

### ISSUE THREAD

**Issue by beatquantum** [u-sb/nginx-docs#10]
On Ubuntu 22.04, the installation of nginx-extras works fine. But it fails with the quic beta alternative with the following error messages.

root@cyberpro:/etc/apt/sources.list.d# apt install -y nginx-extras
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-extras : Depends: libnginx-mod-http-auth-pam (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-cache-purge (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-dav-ext (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-echo (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-fancyindex (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-geoip (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-geoip2 (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-headers-more-filter (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-image-filter (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-lua (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-perl (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-subs-filter (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-uploadprogress (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-upstream-fair (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-xslt-filter (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-mail (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-nchan (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-stream (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-stream-geoip (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-stream-geoip2 (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: libnginx-mod-http-ipdb (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
                Depends: nginx-common (= 1.23.4-1nwtfquic+308quic1+jammy2) but 1.23.4-1nwtf+310+jammy1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by msg7086** [comment]
`1.23.4-1nwtf+310+jammy1` is a bigger version number than `1.23.4-1nwtfquic+308quic1+jammy2`. If you have both repo enabled, or if you have installed regular nginx, you would have to either remove them first and/or allow downgrade.

Make sure you remove those `libnginx-mod-*` if you only removed nginx package itself.

**Comment by beatquantum** [comment]
Got it. Thanks. I just started with a completely fresh Ubuntu 22.04 installation and there was no error in installing the quic version.
