### ISSUE TITLE
Nginx upgrades

### ISSUE THREAD

**Issue by beatquantum** [u-sb/nginx-docs#11]
Hello,
Thanks for your excellent work.
Please could you clarify your release frequency when new nginx mainline versions are available.  For example, now 1.27.1 is available.

**Comment by msg7086** [comment]
Reasonable efforts basis from volunteers.

**Comment by msg7086** [comment]
It has been delayed due to the needs to update to PCRE2 on Trixie, and Nginx API changes.

**Comment by Showfom** [comment]
We have upgraded Nginx to 1.27.1
